sudo: false # build start faster by docker
language: node_js
node_js:
  - 6
cache:
  yarn: true
  directories:
    - ~/.yarn-cache
    - node_modules
install:
  - yarn install
script:
  - yarn run lint
  - yarn run jest -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
