export const STORE_REHYDRATE = 'persist/REHYDRATE';

export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REMOVE_ALL_ALERT = 'REMOVE_ALL_ALERT';

export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_USER = 'AUTH_USER';

export const SET_BRANCHES = 'SET_BRANCHES';
export const SET_SELECTED_BRANCH = 'SET_SELECTED_BRANCH';
export const CLEAR_BRANCH = 'CLEAR_BRANCH';

export const SET_STORE_DETAIL = 'SET_STORE_DETAIL';
export const SET_BUFFER_TIME = 'SET_BUFFER_TIME';
export const SET_STORE_OPEN_STATUS = 'SET_STORE_OPEN_STATUS';
export const CLEAR_STORE = 'CLEAR_STORE';

export const SET_NEW_ORDER_FULFILLMENTS = 'SET_NEW_ORDER_FULFILLMENTS';
export const SET_PREPARING_ORDER_FULFILLMENTS = 'SET_PREPARING_ORDER_FULFILLMENTS';
export const UNLOAD_ORDER_FULFILLMENT = 'UNLOAD_ORDER_FULFILLMENT';

export const FULFILLMENT_CHANGED = 'FULFILLMENT_CHANGED';
export const UNLOAD_FULFILLMENT = 'UNLOADD_FULFILLMENT';

export const SET_DEPAERTMENTS = 'SET_DEPAERTMENTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const CHANGE_PRODUCT_STATUS = 'CHANGE_PRODUCT_STATUS';
export const SET_SEARCH_PRODUCTS = 'SET_SEARCH_PRODUCTS';
export const CLEAR_SEARCH_PRODUCTS = 'CLEAR_SEARCH_PRODUCTS';
export const APPEND_PRODUCTS_TO_DEPARTMENT = 'APPEND_PRODUCTS_TO_DEPARTMENT';
export const APPEND_PRODUCTS_TO_CATEGORY = 'APPEND_PRODUCTS_TO_CATEGORY';
export const NAVIGATION = 'Navigation/NAVIGATE';

export const SET_JOB_HISTORY = 'SET_JOB_HISTORY';
export const CLEAN_JOB_HISTORY = 'CLEAN_JOB_HISTORY';

export const SET_PRINTER_DETAIL = 'SET_PRINTER_DETAIL';
export const CLEAR_PRINTER = 'CLEAR_PRINTER';
export const TOGGLE_AUTO_PRINT = 'TOGGLE_AUTO_PRINT';
