# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NDCHealth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NDCHealth
  pod 'Parse'
  pod 'Fabric'
  pod 'Crashlytics'
  target 'NDCHealthTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NDCHealth-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NDCHealth-tvOS

  target 'NDCHealth-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
