# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaxiDriver' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TaxiDriver
  pod 'Parse'
  pod 'Fabric'
  pod 'Crashlytics'
  target 'TaxiDriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TaxiDriver-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TaxiDriver-tvOS

  target 'TaxiDriver-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
